# Generated by Django 5.0.6 on 2024-07-06 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinks',
            old_name='drinks',
            new_name='drinks_items',
        ),
        migrations.RenameField(
            model_name='drinks',
            old_name='price',
            new_name='price_items',
        ),
    ]
