# Generated by Django 5.0.6 on 2024-07-06 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_drinkscategory_rename_drinks_items_drinks_drink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.drinkscategory'),
        ),
    ]
